version: '2.27'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRSQL_DATABASE: ecosave
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecosave?schema=public
    ports:
      - '8000:8000'
      - '8443:8443'
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:5432 -t 10
        npx prisma generate
        npx prisma migrate dev
        redis-server
        npm run dev

volumes:
  pgdata:
