services:
  db:
    container_name: db
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecosave
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ecosave?schema=public
    ports:
      - '8000:8000'
      - '8443:8443'
    command:
      - bash
      - -c
      - |
        wait-for-it.sh db:5432 -t 10
        npx prisma generate
        npx prisma db pull
        npm run dev

volumes:
  pgdata:
